name: Build and verify

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle build and verify
        run: |
          chmod +x ./gradlew
          ./gradlew buildPlugin
          ./gradlew verifyPlugin
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plugin-build
          path: |
            ./build/distributions